# Generated by Django 5.2.1 on 2026-02-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trips.trip')),
            ],
            options={
                'ordering': ['trip_id', 'seat_number'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'seat_number'), name='uniq_seat_per_trip')],
            },
        ),
    ]
