# Generated by Django 6.0 on 2026-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('departure_time', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=44)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
